# -*- coding: utf-8 -*-
"""Heart_Disease_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrKVF5KU0aMFQ38agSokuNxVVx1Oph5o
"""

import pandas as pd

data = pd.read_csv('heart.csv')
data.head() # displays top 5 rows of the dataset.

data.isnull().sum() # checks missing value in the dataset.

data_dup = data.duplicated().any() #takes care of duplicate values.
data_dup
#the output is true, that means there's duplicate data.

#To remove duplicate data we perform the following code:

data = data.drop_duplicates()
data_dup = data.duplicated().any()
data_dup #the output is false, that means we have removed/dropped all the duplicates from the dataset.

#Data Preprocessing:

cate_val = []
cont_val = []

for column in data.columns:
  if data[column].nunique() <= 10:
    cate_val.append(column) # if unique values are less that 10 then we can consider them in categorical column.
  else:
    cont_val.append(column) # else in contineous column.

cate_val # categorical columns.

cont_val # contineous columns.

# Encoding of categorical data:
data['cp'].unique()
# Converting the array into binary vector

# 1 0 0 0
# 0 1 0 0
# 0 0 1 0
# 0 0 0 1
cate_val.remove('sex')
cate_val.remove('target') # both of them contains 0 and 1 so we dont need them anymore.
data = pd.get_dummies(data,columns=cate_val,drop_first=True)
data.head()

# Feature Scaling: ALlows us to put our features in the same scale.

from sklearn.preprocessing import StandardScaler

st = StandardScaler()
data[cont_val] = st.fit_transform(data[cont_val])
data.head()

from sklearn.model_selection import train_test_split

# Splitting data into traning set and testing set:

X = data.drop('target', axis=1)
y = data['target']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train

y_train

X_test

y_test

# Logistic Regression:

from sklearn.linear_model import LogisticRegression

log = LogisticRegression()
log.fit(X_train,y_train)

y_pred1 = log.predict(X_test)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1) # it is around 78% accurate on logical regression

# SVC: Support Vector Classifier:

from sklearn import svm
svm = svm.SVC()
svm.fit(X_train,y_train)

y_pred2 = svm.predict(X_test)
accuracy_score(y_test,y_pred2) # it is around 80% accurate on svc

# K-Neighbors Classifier:

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

y_pred3 = knn.predict(X_test)
accuracy_score(y_test,y_pred3) # it is around 73% accurate

score = []

for k in range(1,40):
  knn = KNeighborsClassifier(n_neighbors=k)
  knn.fit(X_train,y_train)
  y_pred = knn.predict(X_test)
  score.append(accuracy_score(y_test,y_pred))

score # accuracy scores of different values of k

knn = KNeighborsClassifier(n_neighbors=2) # for k = 2
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred) # now the accuracy has increase to 80%

# Non-Linear Machine Learning Algos:
data = pd.read_csv('heart.csv')
data.head()

data = data.drop_duplicates()
data.shape

X= data.drop('target', axis=1)
y=data['target']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Decision Tree Classifier:

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

y_pred4 = dt.predict(X_test)
accuracy_score(y_test,y_pred4) # it has a accuracy of 77%

# Random Forest Classifier:

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred5 = rf.predict(X_test)
accuracy_score(y_test,y_pred5) # it has a accuracy of 85%

# Gradient Boosting Classifier:

from sklearn.ensemble import GradientBoostingClassifier

gbc = GradientBoostingClassifier()
gbc.fit(X_train,y_train)
y_pred6 = gbc.predict(X_test)
accuracy_score(y_test,y_pred6) # it has a accuracy of 80%

from sklearn.metrics import accuracy_score
import pandas as pd

final_data = pd.DataFrame({
    'Models': ['LR', 'SVM', 'KNN', 'DT', 'RF', 'GB'],
    'Accuracy': [
        accuracy_score(y_test, y_pred1),
        accuracy_score(y_test, y_pred2),
        accuracy_score(y_test, y_pred3),
        accuracy_score(y_test, y_pred4),
        accuracy_score(y_test, y_pred5),
        accuracy_score(y_test, y_pred6)
    ]
})

final_data

# Bar Plot:

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(x='Models', y='Accuracy', data=final_data)
plt.title("Model Accuracy Comparison")
plt.show()

X = data.drop('target',axis=1)
y = data['target']

X.shape

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X,y)

# Prediction on new data:

new_data = pd.DataFrame({
    'age': 52,
    'sex': 1,
    'cp': 0,
    'trestbps': 125,
    'chol': 212,
    'fbs': 0,
    'restecg': 1,
    'thalach': 168,
    'exang': 0,
    'oldpeak': 1.0,
    'slope': 2,
    'ca': 2,
    'thal': 3
}, index=[0])

new_data

p = rf.predict(new_data)
if p[0] == 0 :
  print("No Disease")
else:
  print("Disease")

# Saving Model using Joblib:

import joblib

joblib.dump(rf, 'model_joblib_heart')
model = joblib.load('model_joblib_heart')
model.predict(new_data)

# GUI

from IPython.display import HTML, display

display(HTML("""
<style>
/* center entire UI */
.widget-area {
    display:flex;
    justify-content:center;
}

/* main card */
.card {
    background:#ffffff;
    padding:30px 40px;
    border-radius:22px;
    box-shadow:0 20px 40px rgba(0,0,0,0.08);
    width:360px;
    font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
}

/* title */
.title {
    font-size:22px;
    font-weight:600;
    text-align:center;
    margin-bottom:20px;
}

/* labels */
.widget-label {
    font-size:13px !important;
    color:#666 !important;
}

/* inputs */
input, select {
    border-radius:12px !important;
}

/* toggle buttons */
.widget-toggle-buttons button {
    border-radius:12px !important;
    padding:8px 18px !important;
    margin:4px !important;
    border:none !important;
    background:#f2f2f2 !important;
    color:#333 !important;
    font-weight:500 !important;
}

/* selected toggle */
.widget-toggle-buttons button.mod-active {
    background:black !important;
    color:white !important;
}

/* predict button */
.predict-btn button {
    background:black !important;
    color:white !important;
    border-radius:14px !important;
    padding:12px !important;
    font-weight:600 !important;
    letter-spacing:0.5px;
}

/* result text */
.result {
    text-align:center;
    margin-top:15px;
    font-size:18px;
    font-weight:600;
}
</style>
"""))

import ipywidgets as widgets

age = widgets.IntText(value=52, description="Age")
sex = widgets.ToggleButtons(options=[('Female',0),('Male',1)], description="Sex")
cp = widgets.Dropdown(options=[0,1,2,3], description="Chest Pain")
trestbps = widgets.IntText(value=120, description="BP")
chol = widgets.IntText(value=200, description="Cholesterol")
fbs = widgets.ToggleButtons(options=[('No',0),('Yes',1)], description="Sugar")
restecg = widgets.Dropdown(options=[0,1,2], description="ECG")
thalach = widgets.IntText(value=150, description="Max HR")
exang = widgets.ToggleButtons(options=[('No',0),('Yes',1)], description="Angina")
oldpeak = widgets.FloatText(value=1.0, description="Oldpeak")
slope = widgets.Dropdown(options=[0,1,2], description="Slope")
ca = widgets.Dropdown(options=[0,1,2,3], description="Vessels")
thal = widgets.Dropdown(options=[1,2,3], description="Thal")

button = widgets.Button(description="Predict")
button.add_class("predict-btn")
output = widgets.HTML()

def predict_disease(b):
    new_data = pd.DataFrame({
        'age': age.value,
        'sex': sex.value,
        'cp': cp.value,
        'trestbps': trestbps.value,
        'chol': chol.value,
        'fbs': fbs.value,
        'restecg': restecg.value,
        'thalach': thalach.value,
        'exang': exang.value,
        'oldpeak': oldpeak.value,
        'slope': slope.value,
        'ca': ca.value,
        'thal': thal.value
    }, index=[0])

    pred = model.predict(new_data)[0]

    if pred == 0:
        output.value = "<div class='result' style='color:#16a34a;'>✓ No Heart Disease Risk</div>"
    else:
        output.value = "<div class='result' style='color:#dc2626;'>⚠ Heart Disease Risk</div>"

button.on_click(predict_disease)

form = widgets.VBox([
    widgets.HTML("<div class='title'>Heart Risk Predictor</div>"),
    age, sex, cp, trestbps, chol,
    fbs, restecg, thalach,
    exang, oldpeak, slope, ca, thal,
    button, output
])

display(HTML("<div class='widget-area'><div class='card'></div></div>"))
display(form)